name: Check pipelines

on: [pull_request]

jobs:
  check-pipelines:
    name: Check vertex pipelines and config files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get vertex-deployer from remote
        run: |
          gsutil cp gs://vertex-deployer/vertex_deployer-0.2.0.tar.gz .

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install ./vertex_deployer-0.2.0.tar.gz

      - name: Check pipelines
        run: |
          vertex-deployer check --all --raise-error
