site_name: Vertex Pipelines Deployer
repo_name: artefactory/vertex-pipelines-deployer
repo_url: https://github.com/artefactory/vertex-pipelines-deployer

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/artefact-favicon.png
  font:
    text: Oxygen
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: pink
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: cyan
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra:
  generator: false
  analytics:
    provider: google
    property: G-7REH78BCSD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1@
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/artefactory-skaff/skaff-repo-template/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">opening an issue</a>.

extra_css:
  - stylesheets/skaff.css

nav:
  - Vertex Deployer:
    - Get Started: index.md
    - Prerequisites & Setup: setup.md
    - Folder Structure: folder_structure.md
    - Basic Usage: usage.md
  - Advanced User Guide:
    - Vertex DevOps: advanced/advanced_user_guide.md
    - Understand settings and configurations: advanced/configuration.md
  - CLI Reference: CLI_REFERENCE.md
  - API Documentation:
    - VertexPipelinesDeployer: api/vertex_deployer.md
    - pipeline_checks: api/pipeline_checks.md
    - utils: api/utils.md
  - Contributing: contributing.md
  - Changelog: changelog.md
