site_name: Vertex Pipelines Deployer
repo_name: artefactory/vertex-pipelines-deployer
repo_url: https://github.com/artefactory/vertex-pipelines-deployer

theme:
  name: material
  logo: assets/Artefact-AI-is-about-People-logo-1200x424.png
  favicon: assets/artefact-favicon.png
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: pink
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: cyan
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tooltips
  - content.tabs.link
  - content.code.annotate
  - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Vertex Deployer:
    - Get Started: index.md
    - Prerequisites & Setup: setup.md
    - Folder Structure: folder_structure.md
    - Basic Usage: usage.md
  - Advanced User Guide:
    - Vertex DevOps: advanced_user_guide.md
    - Understand settings and configurations: configuration.md
  - CLI Reference: CLI_REFERENCE.md
  - Contributing: contributing.md
  - Changelog: changelog.md
