site_name: Vertex Pipelines Deployer
repo_name: artefactory/vertex-pipelines-deployer
repo_url: https://github.com/artefactory/vertex-pipelines-deployer

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tooltips
  - navigation.tabs

plugins:
  - search
  - techdocs-core

nav:
  - Get Started:
    - Welcome: index.md
    - Installation: install.md
    - Prerequisites & Setup: setup.md
    - Basic Usage: usage.md
  - Advanced User Guide: advanced_user_guide.md
  - CLI Reference: CLI_REFERENCE.md
  - Contributing: contributing.md
  - Changelog: changelog.md
