site_name: Vertex Pipelines Deployer
repo_name: artefactory/vertex-pipelines-deployer
repo_url: https://github.com/artefactory/vertex-pipelines-deployer

plugins:
  - techdocs-core

nav:
  - Get Started:
    - Welcome: index.md
    - Installation: install.md
    - Prerequisites & Setup: setup.md
    - Basic Usage: usage.md
  - Advanced User Guide: advanced_user_guide.md
  - CLI Reference: CLI_REFERENCE.md
  - Contributing: contributing.md
  - Changelog: changelog.md
