name: CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_call:

jobs:
  ci:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install requirements
        run: uv sync

      - name: Run Pre commit hooks
        run: make format-code

      - name: Run tests
        run: make run-tests

  cli-integration-tests:
    name: Launching CLI Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install requirements
        run: uv sync

      - name: Test root command
        run: |
          cd example
          uv run --project .. vertex-deployer --version

      - name: Test config command
        run: |
          cd example
          uv run --project .. vertex-deployer config --all

      - name: Test list command
        run: |
          cd example
          uv run --project .. vertex-deployer list --with-configs

      - name: Test check command
        run: |
          cd example
          uv run --project .. vertex-deployer check --all

      - name: Test deploy command
      # Cannot check more than compile action here, need GCP environment for upload, run, schedule
        run: |
          cd example
          uv run --project .. vertex-deployer -log DEBUG deploy dummy_pipeline broken_pipeline --compile --env-file example.env --skip-validation

      - name: Test create command
        run: |
          cd example
          uv run --project .. vertex-deployer create test_pipeline --config-type py
          [ -e example/vertex/pipelines/test_pipeline.py ] && echo 1 || echo 0
