name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: make download-poetry

      - name: Set up pip cache
        uses: actions/cache@v3.2.4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

      - name: Set Poetry Path
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH


      - name: Install requirements
        run: |
          poetry run pip install --upgrade pip
          poetry install

      - name: Run Pre commit hooks
        run: make format-code

      - name: Run tests
        run: make run-tests
