name: Deploy doc to GitHub Pages

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
    python-version: "3.10"

jobs:
  deploy-doc:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4

      - name: Set up Python ${{ env.python-version }}
        run: uv python install ${{ env.python-version }}

      - name: Install requirements
        run: uv sync --group docs

      - name: Deploying MkDocs documentation
        run: |
          uv run mkdocs build
          uv run mkdocs gh-deploy --force
