name: Deploy doc to GitHub Pages

on:
  workflow_run:
    workflows: ["CI and Release on main"]
    types: [completed]

env:
    python-version: "3.10"

jobs:
  deploy-doc:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install poetry
        run: make download-poetry

      - name: Set up pip cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ env.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

      - name: Set Poetry Path
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH


      - name: Install requirements
        run: |
          poetry run pip install --upgrade pip
          poetry install --only docs

      - name: Deploying MkDocs documentation
        run: |
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force
